#!/bin/bash
#checking if yay is installed and installing it if it isn't
echo "this script requires yay"
if pacman -Qs yay > /dev/null ;
    then ;
    echo "yay is already installed, continuing"
else ;
echo "to install yay, git and base-devel are required"
if pacman -Qs git > /dev/null ;
    then ;
    echo "git is already installed, continuing"
else ;
echo "installing git"
sudo pacman -S git
echo "git is installed"
fi ;
if pacman -Qs base-devel > /dev/null ;
    then ;
    echo "base-devel is already installed, continuing"
else ;
echo "installing base-devel"
sudo pacman -S base-devel
echo "base-devel is installed"
fi
git clone https://aur.archlinux.org/yay-bin.git ;
cd yay-bin ;
makepkg -si ;
cd ~ ;
exit